name: GraalVM Native Image builds

on:
  push:
    branches:
      - master

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify

  build:
    needs: verify
    name: Build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          {
            name: ubuntu-latest,
            binary-file-start: "fx-demo_",
            jpackage-binary-file-ending: "_amd64.deb",
            graal-binary-file-ending: "",
            file-modifier: "-linux"
          },
          {
            name: windows-latest,
            binary-file-start: "PublicDemoName-",
            jpackage-binary-file-ending: ".exe",
            graal-binary-file-ending: ".exe",
            file-modifier: "-win"
          }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build jpackage with Maven
        run: |
          mvn --batch-mode --update-snapshots clean compile javafx:jlink jpackage:jpackage

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dist/${{ matrix.os.binary-file-start }}0.0.1${{ matrix.os.jpackage-binary-file-ending }}
          asset_name: ${{ matrix.os.binary-file-start }}0.0.1-setup${{ matrix.os.jpackage-binary-file-ending }}
          overwrite: true
          tag: jpackage
          release_name: native image with jpackage


      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          version: 'latest'

      - name: Build fat jar with Maven
        run: mvn --batch-mode --update-snapshots clean compile copy-dependencies:copy-dependencies make-assembly:single

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/fx-demo.jar
          asset_name: fx-demo${{ matrix.os.file-modifier }}.jar
          overwrite: true
          tag: fat-jar
          release_name: fat jar

      - name: Build native image
        run: native-image -jar target/fx-demo.jar

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fx-demo${{ matrix.os.graal-binary-file-ending }}
          asset_name: fx-demo${{ matrix.os.file-modifier }}${{ matrix.os.graal-binary-file-ending }}
          overwrite: true
          tag: graalvm
          release_name: native image with graalvm
