name: Native Image Builds

on:
  push:
    branches:
      - master

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify

  build-with-jpackage:
    needs: verify
    name: Build on ${{ matrix.os.name }} with jpackage ${{ matrix.os.maven-profile }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, out-dir: false, binary-file-name: "fx-demo_0.0.1_amd64.deb", release-name: "fx-demo_0.0.1_amd64.deb", maven-profile: "-P linux-deb" },
          { name: ubuntu-latest, out-dir: true, binary-file-name: "PublicDemoName", release-name: "PublicDemoName-linux", maven-profile: "-P app-image" },
          { name: windows-latest, out-dir: false, binary-file-name: "PublicDemoName-0.0.1.exe", release-name: "PublicDemoName-0.0.1-setup.exe", maven-profile: "-P windows-exe" },
          { name: windows-latest, out-dir: true, binary-file-name: "PublicDemoName", release-name: "PublicDemoName-0.0.1-standalone.exe", maven-profile: "-P app-image" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -P jpackage ${{ matrix.os.maven-profile }} --batch-mode --update-snapshots clean compile javafx:jlink jpackage:jpackage
          ls target/dist/
          zip -r ${{ matrix.os.release-name }}.zip target/dist/${{ matrix.os.binary-file-name }}

      - name: Upload binary to release
        if: ${{ matrix.os.out-dir == false }}
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dist/${{ matrix.os.binary-file-name }}
          asset_name: ${{ matrix.os.release-name }}
          overwrite: true
          tag: jpackage
          release_name: native image with jpackage
      - name: Upload binary to release
        if: ${{ matrix.os.out-dir == true }}
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ matrix.os.release-name }}.zip
          asset_name: ${{ matrix.os.release-name }}.zip
          overwrite: true
          tag: jpackage
          release_name: native image with jpackage

  build-with-graalvm:
    needs: verify
    name: Build on ${{ matrix.os.name }} to fat jar and with GraalVM
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, binary-file-ending: "", file-modifier: "-linux" },
          { name: windows-latest, binary-file-ending: ".exe", file-modifier: "-win" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          version: 'latest'

      - name: Build with Maven
        run: mvn -P fat-jar --batch-mode --update-snapshots clean install package

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/fx-demo.jar
          asset_name: fx-demo${{ matrix.os.file-modifier }}.jar
          overwrite: true
          tag: fat-jar
          release_name: fat jar

      - name: Build native image
        run: native-image -jar target/fx-demo.jar

      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fx-demo${{ matrix.os.binary-file-ending }}
          asset_name: fx-demo${{ matrix.os.file-modifier }}${{ matrix.os.binary-file-ending }}
          overwrite: true
          prerelease: true
          tag: graalvm
          release_name: native image with graalvm
