name: GraalVM Native Image builds

on:
  push:
    branches:
      - master

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify

  build-with-jpackage:
    needs: verify
    name: Build on ${{ matrix.os.name }} with jpackage
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, binary-file-start: "fx-demo_", binary-file-ending: "_amd64.deb" },
          { name: windows-latest, binary-file-start: "PublicDemoName-", binary-file-ending: "-setup.exe" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn -P jpackage --batch-mode --update-snapshots clean compile javafx:jlink jpackage:jpackage

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dist/${{ matrix.os.binary-file-start }}0.0.1${{ matrix.os.jpackage-binary-file-ending }}
          asset_name: ${{ matrix.os.binary-file-start }}0.0.1-setup${{ matrix.os.jpackage-binary-file-ending }}
          overwrite: true
          tag: jpackage
          release_name: native image with jpackage

  build-with-graalvm:
    needs: verify
    name: Build on ${{ matrix.os.name }} to fat jar and with GraalVM
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, binary-file-ending: "", file-modifier: "-linux" },
          { name: windows-latest, binary-file-ending: ".exe", file-modifier: "-win" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          version: 'latest'

      - name: Build with Maven
        run: mvn -P fat-jar --batch-mode --update-snapshots clean install package

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/fx-demo.jar
          asset_name: fx-demo${{ matrix.os.file-modifier }}.jar
          overwrite: true
          tag: fat-jar
          release_name: fat jar

      - name: Build native image
        run: native-image -jar target/fx-demo.jar

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fx-demo${{ matrix.os.binary-file-ending }}
          asset_name: fx-demo${{ matrix.os.file-modifier }}${{ matrix.os.binary-file-ending }}
          overwrite: true
          tag: graalvm
          release_name: native image with graalvm
