name: GraalVM Native Image builds

on:
  push:
    branches:
      - master
      - jpackage

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify

  build:
    needs: verify
    name: Build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: macos-latest, binary-file-ending: "", file-modifier: "-mac" },
          { name: windows-latest, binary-file-ending: ".exe", file-modifier: "-win" },
          { name: ubuntu-latest, binary-file-ending: "", file-modifier: "-linux" }
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean compile javafx:jlink jpackage:jpackage
          ls -al
          cd target/dist
          ls -al

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: noel${{ matrix.os.binary-file-ending }}
          asset_name: noel${{ matrix.os.file-modifier }}${{ matrix.os.binary-file-ending }}
          prerelease: true
          overwrite: true
          tag: dev
          release_name: dev release
