name: GraalVM Native Image builds

on:
  push:
    branches:
      - master
      - jpackage

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify

  build-with-jpackage:
    needs: verify
    name: Build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, binary-file-start: "noel_", binary-file-ending: "_amd64.deb" },
          { name: windows-latest, binary-file-start: "NoEl-", binary-file-ending: ".exe" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean compile javafx:jlink jpackage:jpackage
          cd target/dist
          ls

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dist/${{ matrix.os.binary-file-start }}0.0.1${{ matrix.os.binary-file-ending }}
          asset_name: ${{ matrix.os.binary-file-start }}0.0.1${{ matrix.os.binary-file-ending }}
          prerelease: true
          overwrite: true
          tag: dev-jpackage
          release_name: dev release (native image with jpackage)

  build-with-graalvm:
    needs: verify
    name: Build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: ubuntu-latest, binary-file-ending: "", file-modifier: "-linux" },
          { name: windows-latest, binary-file-ending: ".exe", file-modifier: "-win" }
        ]
    steps:
      - uses: actions/checkout@v4

      - name: Change to GraalVM config
        run: |
          rm src/main/java/module-info.java
          rm pom.xml
          mv fat-jar-pom.xml pom.xml

      - name: Setup graalvm
        uses: graalvm/setup-graalvm@v1
        with:
          java-version: '21'
          distribution: 'graalvm'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
          version: 'latest'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots clean install package

      - name: Upload jar to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/noel.jar
          asset_name: noel${{ matrix.os.file-modifier }}.jar
          prerelease: true
          overwrite: true
          tag: dev-fat-jar
          release_name: dev release (fat jar)

      - name: Build native image
        run: native-image -jar target/noel.jar

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: noel${{ matrix.os.binary-file-ending }}
          asset_name: noel${{ matrix.os.file-modifier }}${{ matrix.os.binary-file-ending }}
          prerelease: true
          overwrite: true
          tag: dev-graalvm
          release_name: dev release (native image with graalvm)