name: GraalVM Native Image builds

on:
  push:
    branches:
      - master
      - jpackage

jobs:
  verify:
    name: Verify project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Verify with Maven
        run: mvn --batch-mode --update-snapshots verify

  build:
    needs: verify
    name: Build on ${{ matrix.os.name }}
    runs-on: ${{ matrix.os.name }}
    strategy:
      matrix:
        os: [
          { name: windows-latest, binary-file-start: "NoEl", binary-file-ending: ".exe" },
          { name: ubuntu-latest, binary-file-start: "noel", binary-file-ending: "amd64.deb" }
        ]
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          mvn clean compile javafx:jlink jpackage:jpackage
          cd target/dist
          ls

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: target/dist/${{ matrix.os.binary-file-start }}_0.0.1_${{ matrix.os.binary-file-ending }}
          asset_name: ${{ matrix.os.binary-file-start }}_0.0.1_${{ matrix.os.binary-file-ending }}
          prerelease: true
          overwrite: true
          tag: dev-jpackage
          release_name: dev release with jpackage
